version: '3.7'

services:

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.6
    ports:
      - "8085:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/vue_realm.json
    volumes:
      - "./vue_realm.json:/tmp/vue_realm.json"
